DEBUG = True
TEMPLATE_DEBUG = DEBUG
ADMINS = ()
MANAGERS = ADMINS
SITE_ID = 1
USE_I18N = False
USE_L10N = True
MEDIA_ROOT = ''
MEDIA_URL = ''
SECRET_KEY = '&s6=1(=*qj9fw#1*(&b!!3d^gs5m60$c^!15jtu1ht9bf#2fsx'
TEMPLATE_LOADERS = ()
MIDDLEWARE_CLASSES = ()
ROOT_URLCONF = 'imgcrnch.urls'
TEMPLATE_DIRS = ()
INSTALLED_APPS = ()

IMG_CACHE_PATH = "/tmp/"
IMG_CRNCH_QUALITY = 5